models:
  - MBA: Mac Book Air
  - MBP: Mac Book Pro
screen sizes:
  - 15 # found on MacBook Air
  - 15.4 # found on MacBook Pro
  - 14.2 # found on MacBook Pro 14-inches (model A2442)
colors:
  - SG: Space Grey # found on MacBook Pro 14-inches (model A2442)
  - SPG: Space Grey # found on MacBook Air 15-inches
  - SLV: Silver
  - GLD: Gold
  - SL: Stellar Light
cpus:
  - 8C CPU: 8 cores Apple Silicon
  - 10C CPU: 10 cores Apple Silicon
  - 3.76C: Intel Core i5 9600K, 3.7 Ghz # found on iMac 27" Retina 5K 2019
  - 2.53: Intel Core i5, 2.53 Ghz
  - 2.9Ghz: Intel Core i9, 2.9 Ghz
gpus:
  - 10C GPU: 10 cores Apple Silicon
  - 16C GPU: 16 cores Apple Silicon
  - Radeon Pro 460: AMD Radeon Pro 460
  - RP580X: AMD Radeon Pro 580X
ram sizes:
  - 16GB: 16GB, soldered on the logic board
  - 32GB: 32GB, soldered on the logic board
  - 2x2GB: 2 sticks of 2GB (4GB total)
storage sizes:
  - 1TB: 1000GB
  - 512GB: 512GB
  - 500: 500GB
  - 3TBFD: 3TB, fusion drive
keyboards:
  - KB-B: British English (QWERTY) ??
  - KB-D: German (QWERTZ)
  - KB-F: French (AZERTY)
  - KB-SF: Swiss French (QWERTZ)
  - KB-US: US English (QWERTY)
  - KB-TA: Taiwan
  - WLKB-F: French (AZERTY), with numeric pad # found on iMac 27" Retina 5K 2019
other locales: # some people on the web say it's "the country where it was sold in / sold to", but it's not exactly that, since Macs sold in France are "/BEL"…
  - BEL: Belgium ??? # found on Macs sold in France !!!, either with KB-F or KB-SF
  - DEU: Deutschland (Germany)
  - GBR: Great Britain
  - TWN: Taïwan ??? # found on Macs with KB-TA
  - ZEE: ??? # Seems to be a kind of "others"


